name: test

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Enter the version (tag) to deploy'
        required: true

jobs:
    sample-job:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                aaa: [hoge, fuga]
        
        steps:
            - name: sample
              run: |
                echo "${{ matrix.aaa }}"  